export { default as About } from "./About";
export { default as Home } from "./Home";
export { default as Leaderboard } from "./Leaderboard";
export { default as Quiz } from "./Quiz";
export { default as Results } from "./Results";
export { default as Setup } from "./Setup";
export { default as Lobby } from "./Lobby";
export { default as LobbyEntry } from "./LobbyEntry";
export { default as NotFound } from "./NotFound";
