const db = connect("mongodb://localhost:27017/quiz");

db.scores.drop();

db.scores.insertMany([
  {  username: "Harry", score: 150 },
  {  username: "Zeia", score: 130 },
  {  username: "Jesse", score: 200 },
  {  username: "Rakib", score: 100 },
  {  username: "Marbo", score: 180 },
  {  username: "Spotch", score: 20 },
  {  username: "Boop", score: 10 },
  {  username: "Meep", score: 170 },
  {  username: "Moop", score: 150 },
  {  username: "Spodge", score: 130 },
  {  username: "Bud", score: 250 },
  {  username: "Dude", score: 30 },
  {  username: "Man", score: 80 },
  {  username: "Bro", score: 25 },
  {  username: "Guy", score: 15 },
  {  username: "Fella", score: 175 },
  {  username: "Friend", score: 170 },
  {  username: "Pal", score: 145 },
  {  username: "Buddy", score: 155 },
  {  username: "Fren", score: 125 },
  {  username: "Fam", score: 135 },
  {  username: "Bruv", score: 250 },
  {  username: "Mate", score: 105 },
  {  username: "Main man", score: 110 },
  {  username: "Frendo", score: 130 },
  {  username: "Buddy", score: 185 },
  {  username: "Chum", score: 75 },
  {  username: "Comrade", score: 105 },
  {  username: "Komrade", score: 210 },
]);
